name: Publish
on:
  push:
    branches:
      - master  # Ana branch'e push yapıldığında tetiklenir

jobs:
  build:
    runs-on: ubuntu-latest  # Linux tabanlı build agent kullan

    env:
      buildConfiguration: 'Release'
      dotnetVersion: '9.0.x'  # .NET 9 sürümü
      imageName: 'myapi'  # Docker Image adı
      containerRegistry: 'myregistry.azurecr.io'  # Azure Container Registry (ACR) adı

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      
    - name: 'Setup .NET 9 SDK'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: 'Build Solution'
      run: |
        dotnet restore ./AuthService.API/AuthService.API.csproj
        dotnet build ./AuthService.API/AuthService.API.csproj --configuration Release
    
    - name: 'Publish'
      run: |
        dotnet publish ./AuthService.API/AuthService.API.csproj --configuration Release --no-build --output './publish'
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myauth' # App Service adı
        slot-name: 'production' # Deployment Slot adı
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'